### ISSUE TITLE
BridgeTo blocking events until channel hangup.

### ISSUE THREAD

**Issue by Anber** [danbarua/NEventSocket#1]
> DEBUG 15/02/03 20:00:54 079  [7] - NEventSocket.Channels.Channel:Channel 576fd745-b4af-49ef-8048-4c677f0864d2 is attempting a bridge to user/oper_1
> DEBUG 15/02/03 20:00:54 104  [7] - NEventSocket.OutboundSocket:Sending [sendmsg 576fd745-b4af-49ef-8048-4c677f0864d2
> Event-UUID: 659bb4bd-316f-4094-8667-b901fe02cb88
> call-command: execute
> execute-app-name: bridge
> content-type: text/plain
> content-length: 68
> 
> {origination_uuid='d126f06d-9bc7-4b80-b1f4-b88c0910d293'}user/oper_1
> ]

A-leg hangup here

> DEBUG 15/02/03 20:01:08 763  [26] - NEventSocket.OutboundSocket:Messages Received [command/reply].
> DEBUG 15/02/03 20:01:08 775  [26] - NEventSocket.OutboundSocket:CommandReply received [+OK] for [sendmsg 576fd745-b4af-49ef-8048-4c677f0864d2
> Event-UUID: 659bb4bd-316f-4094-8667-b901fe02cb88
> call-command: execute
> execute-app-name: bridge
> content-type: text/plain
> content-length: 68
> 
> {origination_uuid='d126f06d-9bc7-4b80-b1f4-b88c0910d293'}user/oper_1
> ]
> DEBUG 15/02/03 20:01:08 805  [26] - NEventSocket.OutboundSocket:Messages Received [text/event-plain].
> DEBUG 15/02/03 20:01:08 811  [26] - NEventSocket.OutboundSocket:Events Received [d126f06d-9bc7-4b80-b1f4-b88c0910d293] [ChannelCreate]

FreeSWITCH version: 1.4.15~64bit ( 64bit)

**Comment by Anber** [comment]
Oops… Sorry, I forgot `async` in connection string :)

**Comment by danbarua** [comment]
Nope, that's still an issue, maybe we should make the .Bridge() method set async = true

**Comment by danbarua** [comment]
Yes, that's a gotcha, remember to set async in your dialplan.

**Comment by danbarua** [comment]
I've updated the README. I'm glad someone is giving this library a try, please do let me know if you run into any further issues.

**Comment by danbarua** [comment]
Also, the Channels API is a work in progress so any ideas or feedback would be greatly appreciated.
