### ISSUE TITLE
No response received from Play method EventSocket class

### ISSUE THREAD

**Issue by padmanabanravikumar** [danbarua/NEventSocket#10]
When Play method called just after hang up occurs then there is no response from method.

I've found the following log for this call.

2015-03-07 15:40:26.9263|DEBUG|NEventSocket.InboundSocket|CommandReply received
[-ERR invalid session id [c1cdaeae-ebb0-4f3f-8f75-0f673bfbc046]] for [sendmsg c1
cdaeae-ebb0-4f3f-8f75-0f673bfbc046
Event-UUID: 0cbc2a67-8591-49bc-8f64-abe414744c4f
call-command: execute
execute-app-name: playback
content-type: text/plain
content-length: 29

I think there is a problem in ExecuteApplication method. it only returns response after receiving ChannelExecuteComplete event.

**Comment by danbarua** [comment]
@padmanabanravikumar Thanks for reporting the issue, we'll now return a null EventMessage in this case. I'm not entirely happy with this design, as the CommandReply error message would essentially be swallowed by this. (You'll still get an ApplicationResult with success == false.) I need to come back and revisit this at some point to make it better.
