### ISSUE TITLE
Correction(s) for README?

### ISSUE THREAD

**Issue by RobThree** [danbarua/NEventSocket#16]
The [Outbound Socket Server](https://github.com/danbarua/NEventSocket/blob/master/README.md#outbound-socket-server) example in the [README](https://github.com/danbarua/NEventSocket/blob/master/README.md) has the following code:

``` c#
socket.Events.Where(x => x.EventName == EventName.ChannelHangup)
                    .Take(1)
                    .Subscribe(x => {
                          Console.WriteLine("Hangup Detected on " + x.UUID);
                          socket.Exit();
                      });
```

It took me a while to figure out why, when I set up two calls, **both** hung up if I hung up **either** of them. In the end the solution couldn't be simpler but, as said, it took me a while to figure out what it was. I _think_ the code should read:

``` c#
socket.Events.Where(x => x.EventName == EventName.ChannelHangup && x.UUID == uuid)
                    .Take(1)
                    .Subscribe(x => {
                          Console.WriteLine("Hangup Detected on " + x.UUID);
                          socket.Exit();
                      });
```

Notice the `Where` clause where I added `&& x.UUID == uuid`. (Maybe use a `string.CompareOrdinal` or equivalent, but you get the idea).

Also: the "await await" in `await await socket.SubscribeEvents();` should, I guess, read: `await Task.Run(() => socket.SubscribeEvents());`. If I use "await await" the compiler says: _`Cannot await void`_ on that particular line and also says _`Cannot convert lambda expression to type 'System.IObserver<NEventSocket.OutboundSocket>`_ because it is not a delegate type*" on the `async socket =>` line.

Please correct me if I'm wrong.

**Comment by danbarua** [comment]
Hi,
yes that's correct.

I've discovered that using `async full` in the dial plan causes an outbound socket to receive  events for _all_channels, not just the channel that launched the socket.

We can correct this in the channel api by applying filters, you'd probably want to leave off `full` with the low-level outbound socket api unless you need to control other channels. Or you could just apply a [filter](https://freeswitch.org/confluence/display/FREESWITCH/mod_event_socket#mod_event_socket-filter).

`client.Filter(HeaderNames.UniqueId, uuid);`

**Comment by danbarua** [comment]
There's more issues with documentation, for example, `socket.SubscribeEvents()` is required, otherwise dial plan applications will never receive the `CHANNEL_EXECUTE_COMPLETE` event.
We could automatically subscribe to events on socket init, like we do in the channels api but I need to find the right balance between ease of use and forcing my opinions on users. We can be more opinionated in the high-level api.

**Comment by RobThree** [comment]
> We can correct this in the channel api by applying filters, you'd probably want to leave off full with the low-level outbound socket api unless you need to control other channels. Or you could just apply a filter.

Both options work for me.

> We could automatically subscribe to events on socket init, like we do in the channels api but I need to find the right balance between ease of use and forcing my opinions on users.

Maybe make it an argument for `Connect()`? Maybe make a `ConnectionOptions` class that has some properties (like "AutosubscribeEvents" or something) that can be passed to the `Connect()` method. This way you leave control up to the user and can "safely assume" some default behaviour for when `Connect()` is called without arguments; be it that it automatically subscribes or that it _doesn't_.

**Edit**
Saw [your commit](https://github.com/danbarua/NEventSocket/commit/6a7e61cd167e04eddd72c36e61d3b136c13059f3) addressing this issue; my suggestion of `await Task.Run(() => socket.SubscribeEvents());` makes to sense I guess; `await socket.SubscribeEvents();` seems to be fine too.

Thanks anyway! I hope to contribute more in the (near) future.

**Comment by danbarua** [comment]
Feel free to drop by https://gitter.im/danbarua/NEventSocket if you want to discuss any ideas or ask questions.

The idea is to dogfood it and add features as the use cases are figured out. Much of FreeSwitch's ESL involves trial-and-error to figure out how the damn thing works.

**Comment by danbarua** [comment]
I've added some more clarifications to the README - at some point I'll get around to writing up some proper documentation as I've learnt quite a bit about the ESL api that isn't explained in the FS documentation.

**Comment by danbarua** [comment]
Readme + example code updated and clarified.
