### ISSUE TITLE
can it build in .net40?

### ISSUE THREAD

**Issue by bushadam** [danbarua/NEventSocket#19]

**Comment by danbarua** [comment]
I will look into creating a .Net 4.0 package, if it is feasible.

**Comment by danbarua** [comment]
[Microsoft has ended support for .Net 4.0.](https://blogs.msdn.microsoft.com/dotnet/2015/12/09/support-ending-for-the-net-framework-4-4-5-and-4-5-1/)

It would probably be too much work for little ROI to support .Net 4.0.
