### ISSUE TITLE
First connection fails if a logger (in my case NLog) is found

### ISSUE THREAD

**Issue by derwasp** [danbarua/NEventSocket#21]
I took this code from your repo, just added NLog package. When `Connect` method is called, an exception is thrown (System.TimeoutException, Message = "No Auth Request received within the specified timeout of 00:00:05.")
If I remove NLog it works just fine.
Sometimes if I call any log method befor calling `Connect` it also works.

I tested this behavior on 2 computers.
VS 2015, .NET 4.5 / 4.5.1 / 4.5.2

```
public class Program
{
    static void Main(string[] args)
    {
        ApiTest();
        Console.ReadLine();
    }

    private static async void ApiTest()
    {
        using (var client = await InboundSocket.Connect("192.168.21.100", 8021, "mypassword"))
        {
            Console.WriteLine((await client.SendApi("status")));
            Console.WriteLine((await client.SendApi("blah")));
            Console.WriteLine((await client.SendApi("status")));
        }
    }
```

I thought it might be something wrong with the time needed to initialize the logger for the first time, that is why I created dummy logger with static ctor with Thread.Sleep(2000) inside, but with this one it works just fine.

I hope this explanation is enough and maybe you can help me fixing this ;)

**Comment by derwasp** [comment]
It is also reproducible using the source code.
I tried running `KitchenSink` project, commented out everything except a call to `ApiTest`, so my `Main` looks like this:

```
private static void Main(string[] args)
{
    ApiTest();
    Console.ReadLine();
}
```

And the exception is still there:
![with_nlog](https://cloud.githubusercontent.com/assets/10754345/9544972/9cef3692-4d85-11e5-9434-a019ca417c62.PNG)

And the log messages are:
![with_nlog2](https://cloud.githubusercontent.com/assets/10754345/9545015/014a1b2a-4d86-11e5-95d0-8d6975e1f995.PNG)

If I uncomment the following line:

```
Log.Trace("tesst");
```

It will not throw an exception.

**Comment by danbarua** [comment]
hey @derwasp could you take a look at this issue: https://github.com/danbarua/NEventSocket/issues/8 and see if it's related to yours?

**Comment by danbarua** [comment]
As a work around, you can bump up the timeout value using the static property here: https://github.com/danbarua/NEventSocket/blob/master/src/NEventSocket/Sockets/EventSocket.cs#L87

``` csharp
EventSocket.ResponseTimeout = TimeSpan.FromSeconds(20); //or any value of your choosing
```

**Comment by derwasp** [comment]
Thank you for such a fast response.
As for the workaround: the property you are referencing to is not static `public TimeSpan ResponseTimeOut { get; set; }`, so I think that is not the one I need.
I saw that it is possible to change the timeout in the `Connect` method:

```
 public static async Task<InboundSocket> Connect(
        string host = "localhost", int port = 8021, string password = "ClueCon", TimeSpan? timeout = null)
```

And that is what I did first, before writing here, and just double checked it now. The results are:
1) Setting 20 seconds has no effect, I still have my timeout.
2) Setting 60 seconds results another exception:
![new_exc](https://cloud.githubusercontent.com/assets/10754345/9545932/74254fd6-4d8e-11e5-8b01-15cb3cc21573.PNG)
And the logs are:
![new_exc2](https://cloud.githubusercontent.com/assets/10754345/9545933/7426c5dc-4d8e-11e5-846f-06616fa6a1a9.PNG)

That is why I think that 'any value of my choosing' will not work here, because it timeouts in different place..
As for the issue #8 : I think it relates, and as you said in that thread it sounds like a race condition, but it is hard for me to figure out where, since I am not familiar with Rx =\

Thanks for helping!

**Comment by danbarua** [comment]
Hi, take a look at wrapping your NLog configuration in an AsyncLogger, it
will prevent NLog from blocking NEventSocket's worker threads

**Comment by danbarua** [comment]
As you've foked the code, you can comment out lines 48-52 to remove the timeout behaviour
https://github.com/danbarua/NEventSocket/blob/master/src/NEventSocket/InboundSocket.cs#L48

But I do strongly recommend you configure NLog to log asynchronously otherwise it will have a performance impact.

https://github.com/nlog/NLog/wiki/AsyncWrapper-target

**Comment by derwasp** [comment]
Hello Dan,

I knew the following result but I decided to give it a try:

![commenting_out_timeout](https://cloud.githubusercontent.com/assets/10754345/9566638/cb9465f2-4f0c-11e5-818a-1513a0598979.PNG)

That is expected, since as I said before: it timeouts in another place when I set timeout to be >20 seconds (in previous case it was 60).

As for the NLog: the issue is not with writing, it doesn't take to much time. It just hangs in that place.
Anyway I followed your advice and here is the configuration:

  <nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" autoReload="true">

```
<targets>
  <target xsi:type="AsyncWrapper"
    name="wrappedConsole"
    queueLimit="10000"
    timeToSleepBetweenBatches="50"
    batchSize="100"
    overflowAction="Grow">
    <target name="console" type="Console" layout="${date:format=HH\:mm\:ss}|${level}|${message}|${exception:format=type,message}" />
  </target>
</targets>

<rules>
  <logger name="*" minlevel="Trace" writeTo="wrappedConsole" />
</rules>
```

  </nlog>

But still, no change.

I just want to emphasize that if I call the logger at least once before it goes to create an InboundSocket everything works just fine.

```
public static async Task<InboundSocket> Connect(
        string host = "localhost", int port = 8021, string password = "ClueCon", TimeSpan? timeout = null)
    {
        Log.Trace("tesst"); // adding this line fixes the issue

        var socket = new InboundSocket(host, port, timeout);
```

But that is for sure not the solution.

**Comment by danbarua** [comment]
Hi, take a look at issue 20 #20 

It seems Console.ReadLine() causes subscription callbacks to block.

Can you try replacing `Console.ReadLine()` with this:

``` csharp
ColorConsole.WriteLine("Press CTRL+C to exit".OnGreen());
                await Observable.FromEventPattern<ConsoleCancelEventHandler, ConsoleCancelEventArgs>(
                    h => Console.CancelKeyPress += h,
                    h => Console.CancelKeyPress -= h).ToTask();
```

**Comment by derwasp** [comment]
Hey Dan,

thanks for the feedback, it gave me some ideas, but not a single one worked ;)

My real application has no `Console.ReadLine()`. But with `Console.ReadLine()` it is 100% reproducible.
And second thing: you can not do `await` inside `Main()`

With that in mind I tried the following using your kitchen sink example:
1)

```
        var res = Task.Run(() => ApiTest());
        res.Wait();
        Console.ReadLine();
```

2)

```
        var task = new Task(ApiTest, TaskCreationOptions.LongRunning);
        task.Start();
        task.Wait();
        Console.ReadLine();
```

3)

```
        new Thread(ApiTest).Start();
        Console.ReadLine();
```

But nothing worked.
I also tried to use `NewThreadScheduler.Default` in `SubscribeOn` methods. I though if everything will work in it's own thread it might help. But no, it didn't help at all.

Wrapping this line `Log.Trace(() => "EventSocket initialized");` to `Task.Run(() => Log.Trace(() => "EventSocket initialized"));` helped. But it is still weird.

**Comment by danbarua** [comment]
OK, would you mind sharing with me your full NLog configuration so I can try and replicate the issue?

**Comment by derwasp** [comment]
Sure! This is full app.config I have.

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <configSections>
    <section name="nlog" type="NLog.Config.ConfigSectionHandler, NLog" />
  </configSections>

  <startup>
    <supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.5" />
  </startup>

  <nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" autoReload="true">

    <targets>
      <target xsi:type="AsyncWrapper"
        name="wrappedConsole"
        queueLimit="10000"
        timeToSleepBetweenBatches="50"
        batchSize="100"
        overflowAction="Grow">
        <target name="console" type="Console" layout=" ${threadid} ${date:format=HH\:mm\:ss}|${level}|${message}|${exception:format=type,message}" />
      </target>
    </targets>

    <rules>
      <logger name="*" minlevel="Trace" writeTo="wrappedConsole" />
    </rules>
  </nlog>

  <runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="System.Reactive.Interfaces" publicKeyToken="31bf3856ad364e35" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-2.2.5.0" newVersion="2.2.5.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="System.Reactive.Core" publicKeyToken="31bf3856ad364e35" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-2.2.5.0" newVersion="2.2.5.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="System.Reactive.Linq" publicKeyToken="31bf3856ad364e35" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-2.2.5.0" newVersion="2.2.5.0" />
      </dependentAssembly>
    </assemblyBinding>
  </runtime>
</configuration>
```

**Comment by derwasp** [comment]
Maybe this could be useful too.

After this line 

```
        Events.Subscribe(x => Log.Trace(() => "Events Received [{0}] [{1}]".Fmt(x.UUID, x.EventName)), ex => { }, () => Log.Info(() => "Events Observable Completed."));
```

I modified code a bit:

```
        messages
            .Where(x => x.ContentType == ContentTypes.AuthRequest)
            .Subscribe(
                x =>
                    {
                        // this one works
                        Log.Trace(() => x.ContentType);
                    });

        Log.Trace(() => "EventSocket initialized");
        messages.Take(1).Do(x =>
                {
                    // never comes here
                    Log.Trace(() => x.ContentType);
                });
```

**Comment by danbarua** [comment]
This won't work:

```
 messages.Take(1).Do(x =>
                {
                    // never comes here
                    Log.Trace(() => x.ContentType);
                });
```

as `.Do()` is meant to cause side effects (namely logging) on a subscription.
But we need to make the observable 'hot' by subscribing to it.

So this should work

```
 messages.Take(1).Subscribe(x =>
                {
                    // never comes here
                    Log.Trace(() => x.ContentType);
                });
```

But this would be better:

```
 messages.FirstAsync().Subscribe(x =>
                {
                    // never comes here
                    Log.Trace(() => x.ContentType);
                });
```

**Comment by danbarua** [comment]
It seems to block even with no NLog targets enabled - there are others who are successfully using NEventSocket with NLog so it should work, I will look into this.

**Comment by derwasp** [comment]
All three variants are not working after `Log.Trace(() => "EventSocket initialized");` anyway. That was my point. But thanks for correcting me though.

If you need me to test whatever else I will be happy to help. Meanwhile I am trying to figure it out myself. Will inform you if I find something.

**Comment by derwasp** [comment]
> I don't get it about 'warming up' the observable. ;)

Read your sentence one more time and now I got it. So nvm ;)

**Comment by derwasp** [comment]
Update from me:

You have a race condition in EventSocket constructor:

```
protected EventSocket(TcpClient tcpClient, TimeSpan? responseTimeOut = null) : base(tcpClient)
```

This line breaks everything:

```
Events.Subscribe(x => Log.Trace(() => "Events Received [{0}] [{1}]".Fmt(x.UUID, x.EventName)), ex => { }, () => Log.Info(() => "Events Observable Completed."));
```

Once you are subscribed here your IObservable is 'hot' and it starts to pump the events out.
You can do `Thread.Sleep(2000)` after this subscription, break in debug after sleep and check `this.recieved`, it will be empty.

That is why sometimes it works, sometimes it does not. The fastest way will be to remove the subscription from `ctor`.

**Comment by danbarua** [comment]
^ that's part of it, just a little bit of fiddling with the `OutboundSocket` and we're good to go

**Comment by danbarua** [comment]
Could you check out the changes from this branch and let me know if it works ok for you?
https://github.com/danbarua/NEventSocket/tree/derwasp-master

**Comment by danbarua** [comment]
This should be fixed in `0.6.5` which is now up on NuGet, could you test and let me know. Thanks.

**Comment by derwasp** [comment]
Hey Dan!
Thanks for that, I will try to test it tomorrow morning and will tell you the results, since I don't have access to the machine I am testing this on.

**Comment by derwasp** [comment]
Just did a couple of tests in my application and everything looks cool.

**Comment by danbarua** [comment]
Glad to hear it :+1:
