### ISSUE TITLE
Event Subscriptions

### ISSUE THREAD

**Issue by danbarua** [danbarua/NEventSocket#23]
Currently an `EventSocket` subscribes to a few events for convenience:

```
private readonly HashSet<EventName> subscribedEvents = new HashSet<EventName>()
{
 EventName.ChannelExecuteComplete, 
 EventName.BackgroundJob, 
 EventName.ChannelHangup, 
 EventName.ChannelAnswer, 
 EventName.ChannelProgress, 
 EventName.ChannelProgressMedia, 
 EventName.ChannelBridge, 
 EventName.ChannelUnbridge
};
```

In high-traffic/high-performance scenarios, users may wish to subscribe to only the minimum events.

Requirement: an `EventSocket` should subscribe to events lazily as and when they are required, for example, when I do an `Originate` it should, if necessary, subscribe to the `BackgroundJob` and `ChannelExecuteComplete` events if not already done so.

**Comment by gregoriusus** [comment]
Maybe this is not necessary. Developer need not to call SubscribeEvents, but can subscribe manually via SendCommand ("event plain xxxxxxxx")

**Comment by danbarua** [comment]
There's an experimental branch where this is implemented:
https://github.com/danbarua/NEventSocket/compare/issue-23

**Comment by danbarua** [comment]
Closed
