### ISSUE TITLE
How do I send uuid_transfer command?

### ISSUE THREAD

**Issue by Eternal21** [danbarua/NEventSocket#34]
I don't see a Transfer method on InboundSocket.  I'm basically trying to convert an ongoing call into a conference, so that I can 'conference in' another person.  I plan on doing it by transfering both legs into a conference room first.  I'm assuming the specific 'Transfer()' function has not been implemented, but the workaround can be running a transfer application via another command?  Thanks.

Also - how do I label this issue as a Question (since it's not a bug)?

**Comment by danbarua** [comment]
Hi,

Are you using channels? If it's not exposed on the Channel obejct itself you can use `channel.Advanced.Socket` on v1.0.2 or just `channel.Socket` on v2.0 to get at the underlying `EventSocket` object.

With an `EventSocket` instance you can do anything, Channels just abstracts a lot of the nitty-gritty away from you. `socket.Api("uuid_transfer", "<UUID> extension_to_transfer_to);` is what you want.

**Comment by danbarua** [comment]
`transfer` is used for transferring to an extension or part of the xml dialplan. At full socket-level control you maybe want to execute a dialplan application which is `socket.ExecuteApplication(uuid, application, args)`

**Comment by danbarua** [comment]
Jump in Gitter -> https://gitter.im/danbarua/NEventSocket
I'm online for an hour or so

**Comment by danbarua** [comment]
You can do 
`socket.Api("uuid_transfer", "my_uuid myExtensionOrInlineDialPlanOrWhatever");` - tend to use Api commands for fire-and-forget
or
`await channel.Socket.ExecuteApplication(channel.UUID, "conference", "conference_args");` - this will block until the channel hangs up, and probably throw OperationCanceledException (this is normal on shutdown)
We use `.ExecuteApplication()` when we are wanting to wait for an application to complete with `CHANNEL_EXECUTE_COMPLETE`

**Comment by danbarua** [comment]
If it's listed in here https://freeswitch.org/confluence/display/FREESWITCH/mod_commands it's an API command, though BgApi and Originate are wrapped up in helpers to deal with the underlying complexity for you but there's nothing stopping you creating a command string manually and calling that.

If it's in here it's a dialplan application: https://freeswitch.org/confluence/display/FREESWITCH/mod_dptools

**Comment by Eternal21** [comment]
Thanks.  Didn't see your message yesterday, that was the last thing I posted before logging off for the day.  I'll give it a try and post back with the results.

**Comment by Eternal21** [comment]
Ok, got it working using the following command:  
`await _socket.Api("uuid_transfer", _callUuid + " -both 3000");`

I'm using the demo dialplan, so extension 3000 executes the following built-in conference:

```
    <!--
    start a dynamic conference with the settings of the "default" conference profile in conference.conf.xml
    -->                                                                                                                                                       
    <extension name="nb_conferences">
      <condition field="destination_number" expression="^(30\d{2})$">
    <action application="answer"/>
    <action application="conference" data="$1-${domain_name}@default"/>
      </condition>
    </extension>
```

Now I just need to figure out how to record audio from both.
