### ISSUE TITLE
using InBoundSocket auto outcall problem.

### ISSUE THREAD

**Issue by yojinjin** [danbarua/NEventSocket#35]
here is the main code.

///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
'
// using static socket.
public static InboundSocket socket;

static void Main(string[] args)
{

```
socket = await InboundSocket.Connect("127.0.0.1", 8021, "ClueCon", 0);

//subscribe events......
socket.Events.Where(x => x.EventName == EventName.ChannelAnswer).Subscribe(async y =>
            {
            });
```

}

//in thread auto out call
while (true)
{
.....

InBoundAutoCall(list_ky[j], m_num.Tele, m_num.Id, op);

Thread.Sleep(50);
.....

}

public static async void InBoundAutoCall(string callerno, string tele, int pool_id, OriginateOptions op)
{
    try
    {
        op.CallerIdNumber =  callerno;
        op.CallerIdName = callerno;
        op.HangupAfterBridge = true;
        op.TimeoutSeconds = 20;
        op.ReturnRingReady = true;
        op.ChannelVariables.Add("callerno", callerno);
        op.ChannelVariables.Add("calledno", tele);

```
    var result = await socket.Originate("sofia/gateway/" + callerno + "/" + tele, op);
    if (result.Success)
    {

    }
    else
    {

    }

}
catch (Exception ex)
{

}
```

}`

/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

When the number of concurrent calls, at around 100, there will be a socket problem. Originate returns false. Then I look at the number of freeswitch channels, but the number of channels has been 0. After we close the program, reopen the socket connection, socket can work for a while, but once the amount reached 100 or so, it will appear the above situation.Is something error with us?

regards.

**Comment by danbarua** [comment]
First off, you can investigate the HangupCause property to see why the originate failed.

But I recommend you install a logging library into your project to get a better view of what's going on. NEventSocket uses LibLog which will automatically detect and route log messages to most popular logging libraries. I personally use NLog.

With Trace level logging you get a full picture of all messages flowing through NEventSocket which is useful for debugging, just be sure to adjust the logging level to Info or Warning in production for performance reasons.

If you are having issues with NEventSocket, it always helps to post Trace level log output so we can get an idea of what's going on.

**Comment by yojinjin** [comment]
I tried it yesterday. If we concurrent outbound call using SendCommand method directly launch command Originate, so at the time of concurrent will not appear freeswitch call volume after reaching a certain number, number of freeswitch calls gradually becomes zero. If you call the Originate method of Inbound, the above situation will appear. This may be a problem with the Originate method.

**Comment by yojinjin** [comment]
![calls count 0 not work](https://cloud.githubusercontent.com/assets/4043717/15309942/fd0c9134-1c1d-11e6-8d08-059fe0981602.jpg)
[calls count 0 not work.txt](https://github.com/danbarua/NEventSocket/files/267343/calls.count.0.not.work.txt)
![calls count about 600 work fine](https://cloud.githubusercontent.com/assets/4043717/15309943/fd639f9c-1c1d-11e6-9da8-724e91de3673.png)
[calls count about 600 work fine.txt](https://github.com/danbarua/NEventSocket/files/267344/calls.count.about.600.work.fine.txt)

calls count 0 not work  using Originate method.
calls count about 600  using SendCommand like this.

var originateString = string.Format("{0}{1} {2}", op, "sofia/gateway/88165450/15311111111", "'&park()'");

```
            Guid jobUUID = Guid.NewGuid();

            var backgroundApiCommand = originateString != null
                                           ? "bgapi {0} {1}\nJob-UUID: {2}".Fmt("originate", originateString, jobUUID)
                                           : "bgapi {0}\nJob-UUID: {1}".Fmt("originate", jobUUID);

            await socket.SendCommand(backgroundApiCommand);
```

**Comment by danbarua** [comment]
Please see related issue https://github.com/danbarua/NEventSocket/issues/29 and sample code: https://github.com/danbarua/NEventSocket/blob/master/src/NEventSocket.Examples/Examples/VoiceBlaster.cs

**Comment by danbarua** [comment]
Can you show me the logs for 'calls count 0 not work using Originate method.'?

**Comment by yojinjin** [comment]
https://github.com/danbarua/NEventSocket/files/267343/calls.count.0.not.work.txt

I have uploaded.

**Comment by yojinjin** [comment]
I use SendCommand method to send Concurrent call. now work fine.

**Comment by danbarua** [comment]
@yojinjin seems to be more of an application issue than a library issue - closing for now but re-open if you are still having problems.
