### ISSUE TITLE
Make PlayGetDigitsOptions.digitsRegex public

### ISSUE THREAD

**Issue by m-jepson** [danbarua/NEventSocket#38]
I would like to set a regex for the accepted dtmf input, so I can set a certain logic, for instance where the code has to begin with either a 0 or a 1 and then some numbers and then ends with a 9 or a 0.
I have now used reflection to set the private field digitsRegex, which works as expected, but it would be nicer if the field was just public to begin with.

**Comment by danbarua** [comment]
Thanks for the use case, I hadn't considered that. This will be in the next pre-release build on MyGet.

**Comment by danbarua** [comment]
MyGet doesn't seem to be updating the package feed correctly - I'll look into this - might as well push v2 to NuGet

**Comment by danbarua** [comment]
There was a bug in MyGet's logic for pre-release packages, they've added the latest build to the feed while they work on the bug.
