### ISSUE TITLE
Referenced NuGet packages

### ISSUE THREAD

**Issue by pragmatrix** [danbarua/NEventSocket#42]
This is just a suggestion and it would make it a bit easier (for me) to contribute. As I can see, the CI scripts run an explicit `NuGet restore` and Visual Studio 2015 is now also able to restore the NuGet packages automatically, so I would suggest to remove them from the repository. I am happy to provide a pull request, if this is acceptable.

**Comment by danbarua** [comment]
![image](https://cloud.githubusercontent.com/assets/469192/16085297/85a29438-3313-11e6-9fd0-08b0bfb1756d.png)

Yep, looks like cruft to me.

![image](https://media.giphy.com/media/wvFrJa4aWKuvm/giphy.gif)
