### ISSUE TITLE
ChannelState

### ISSUE THREAD

**Issue by gregoriusus** [danbarua/NEventSocket#47]
CchannelState variable can be null. Header doesn't have value in CUSTOM events
Can you plese set ChannelState property to nullable like AnswerState.

Thank you!

**Comment by danbarua** [comment]
Yep, not everyone is using this for Channel Events, thanks for the catch.

**Comment by danbarua** [comment]
@gregoriusus I am taking a different approach now for V2 - `socket.Events` contains basic Event messages, `socket.ChannelEvents` contains channel events. So issues like this should not come up again in future.
