### ISSUE TITLE
System.Reactive.Core

### ISSUE THREAD

**Issue by gregoriusus** [danbarua/NEventSocket#50]
It looks like MS updated reactive library nuget package to 3.0. With this reference neventsocket project cannot be build. Any plans to support new version of reactive library?

**Comment by danbarua** [comment]
When we do a CI build (from the build script) we ILMerge Reactive Extensions into the library and expose only the `IObservable` interface on the public API (which is in the Base Class Library)

This leaves you free to use whatever version of Rx you are using in your application without conflicts.

With this in mind though, I will take a look at updating the package versions.

**Comment by danbarua** [comment]
Looks like Rx is now CoreCLR compatible https://github.com/Reactive-Extensions/Rx.NET/issues/148#issuecomment-226611683 I'll look into porting to CoreCLR now. LibLog might be a show-stopper.

**Comment by gregoriusus** [comment]
Yes, this is due to  .NET Core compatibility. Also in VS can't select older version of Reactive Extension.

**Comment by danbarua** [comment]
Ah cool. If you're using the output from the build script, the Rx 2.5 dependency is internalized and the public API only exposes `IObservable` so you should be able to use Rx 3.0 outside the library in your own app in the meantime.

**Comment by gregoriusus** [comment]
Ah, I get it. I can build with 2.5, but in referenced project/solution, I can ad reference to 3.0.

**Comment by danbarua** [comment]
That's correct. A bit like how loads of OSS libs have an internal ILMerged `Newtonsoft.Json` buried underneath.
