### ISSUE TITLE
Public member 'Where' on type 'Select(Of BasicMessage,EventMessage)' not found.

### ISSUE THREAD

**Issue by aistosi** [danbarua/NEventSocket#51]
Hello,

I am trying to use this library for the windows service project at my work, but getting the following error:
Public member 'Where' on type 'Select(Of BasicMessage,EventMessage)' not found.

I am using an example for the Inbound Socket Client from the main page. The code looks like this:

```
   Private Async Function SocketSetup() As Task

        goSocket = Await InboundSocket.Connect(ConfigurationManager.AppSettings("Phone_Server_IpAddress"), System.Configuration.ConfigurationManager.AppSettings("Phone_Port"), "ClueCon")

        Dim ApiResponse = Await goSocket.SendApi("status")
        WriteTraceFile(ApiResponse.BodyText, 0)

        Await goSocket.SubscribeEvents(EventName.ChannelHangupComplete)

        goSocket.Events.Where(Function(x) x.EventName = EventName.ChannelHangupComplete).Subscribe(Async Sub(x)

                                                                                                       Await ProcessCall(x.UUID, x.HangupCause)

                                                                                                   End Sub)

    End Function
```

goSocket is a global object. The error happens where it subscribes to events. Am I missing something? I tried in .NET 4.5 and 4.6.1. I got the latest version of System.Reactive.Linq. Can't figure it out.

**Comment by RobThree** [comment]
Forgive me, my VB.Net is a little rusty, but aren't you simply missing one or more [Imports](https://msdn.microsoft.com/en-us/library/7f38zh8x.aspx)?

**Comment by aistosi** [comment]
System.Reactive.Linq is one of the imports. 
https://msdn.microsoft.com/en-us/library/hh211607(v=vs.103).aspx

For some reason I also do not get Intellisense on any of the NEventSocket objects that I create.

**Comment by danbarua** [comment]
That sounds more like a Visual Studio config/environment issue than a lib issue.

Re: namespaces - they're at the top of each example in the ReadMe :)

**Comment by aistosi** [comment]
Dan, I ran the same code in C# and it didn't have this issue. It appears that there might be incompatability with VB.NET, or like you said, something not configured correctly in VB env. Are you aware of any issues that NEventSocket would have with VB?

Probably just gonna create a dll in C# and link up to my vb win service.

**Comment by RobThree** [comment]
Apart from the syntax there's [no (significant) difference](https://en.wikipedia.org/wiki/Comparison_of_C_Sharp_and_Visual_Basic_.NET#Language_comparison) in VB.Net vs C#; it both compiles to the same [CIL](https://en.wikipedia.org/wiki/Common_Intermediate_Language). So, yes, you can compile the C# code to a DLL and reference that. You can also simply include the C# code in your project (you can mix C#/VB.Net (and any other .Net languages for that matter) in a single project (or solution)). But in the end simply using the correct imports etc. should work for VB.Net just as well as it does for C#. I'm 99% sure it's PEBKAC. You could post the code entirely (**note**: minimal testcase preferred over hundreds of lines of code!) so we can easily reproduce your problem and point out any missing imports / mistakes you made.

**Comment by danbarua** [comment]
![image](https://cloud.githubusercontent.com/assets/469192/16982650/f843956c-4e68-11e6-96dd-747a779c3667.png)

No problems with VB intellisense in VS2015 here..

**Comment by aistosi** [comment]
Ok I give up. I just created a sample class library project and copied the code on the front page and getting two errors.

```
using System;
using System.Reactive.Linq;
using System.Threading.Tasks;

using NEventSocket;
using NEventSocket.FreeSwitch;

namespace NEventPSELib
{
    public class NEventPSELib
    {

        public async Task Test()
        {
            using (var socket = await InboundSocket.Connect("localhost", 8021, "ClueCon"))
            {
                var apiResponse = await socket.SendApi("status");
                Console.WriteLine(apiResponse.BodyText);

                //Tell FreeSwitch which events we are interested in
                await socket.SubscribeEvents(EventName.ChannelAnswer);

                //Handle events as they come in using Rx
                socket.Events.Where(x => x.EventName == EventName.ChannelAnswer)
                      .Subscribe(async x =>
                      {
                          Console.WriteLine("Channel Answer Event " + x.UUID);

            //we have a channel id, now we can control it
            await socket.Play(x.UUID, "misc/8000/misc-freeswitch_is_state_of_the_art.wav");
                      });

                Console.WriteLine("Press [Enter] to exit.");
                Console.ReadLine();
            }
        }
    }
}
```

'Observable.Where<TSource>(IObservable<TSource>, Func<TSource, bool>)' is inaccessible due to its protection level  

And

Cannot convert lambda expression to type 'IObserver<EventMessage>' because it is not a delegate type    NEventPSELib    

What the hell am I missing?

**Comment by danbarua** [comment]
What version of .Net are you trying to use? (Right click project -> Properties -> Application) - you can paste a screenshot straight into the textbox and github will upload it for you.

**Comment by aistosi** [comment]
![image](https://cloud.githubusercontent.com/assets/20544404/16988609/f83eb574-4e5e-11e6-848c-4e26cc844259.png)

This is the original VB project. Unfortunately I will not be able to create a C# dll at a time, since it requires a lot of rewriting. You can also see the error at the bottom of the screenshot. 

I am getting intellisense when I specified the type for the connection socket. Looks like Dim <variable_name> and var <variable_name> are not exactly the same in these languages.

**Comment by RobThree** [comment]
I'd start with correcting / fixing the NuGet package version; the warning in your screenshot is pretty clear and also tells you how to fix it (or at least where to get more information on how to fix it).

> Looks like Dim and var are not exactly the same in these languages.

&nbsp;

> Omitting the type in VB.NET (VB9) will implicitly type the variable.
> 
> This is _not_ the same as "option strict off" in previous versions of VB.NET, as the variable is strongly-typed, it's just done so implicitly (like the C# [`var`](https://msdn.microsoft.com/en-us/library/bb383973.aspx?f=255&MSPPError=-2147217396)) keyword.
> 
> ```
> Dim foo = "foo"
> ```
> 
> `foo` is declared as a `String`.
> 
> [Option Infer](http://msdn.microsoft.com/en-us/library/bb384665.aspx) must be **on** in order for this to function properly

[Source](http://stackoverflow.com/a/2478593/215042)

**Comment by danbarua** [comment]
Ah yeah that NuGet error looks like the smoking gun! Well spotted.

**Comment by aistosi** [comment]
So I went in and manually cleaned out all the references to Reactive Extenstions and NEventSocket in the project file, cleaned out packages.config, as well as packages folder. Reinstalled NEventSocket, still no 'Where' function. Installed the latest System.Reactive.Linq and voila, error is gone and can get past it in runtime as well. Does current NEventSocket have an outdated dependency for Reactive Extensions?

**Comment by danbarua** [comment]
NEventSocket internalizes ReactiveExtensions, exposing only `IObservable<T>` on the public API which is in the `System` base class namespace. This means we'll never conflict with whatever version of RX you may be using in your app.

**Comment by aistosi** [comment]
I see. Thank you for the help. Both of you.
