### ISSUE TITLE
Not all CHANNEL_HANGUP_COMPLETE are received

### ISSUE THREAD

**Issue by aistosi** [danbarua/NEventSocket#52]
This is probably more of a FS question but might be related to NEventSocket. Is it possible not to receive all the CHANNEL_HANGUP_COMPLETE events when subscribing using goSocket.Events.Where(Function(x) x.EventName = EventName.ChannelHangupComplete)? Basically we have a windows service, which continually dials records from a DB as they come in. It updates them when we receive CHANNEL_HANGUP_COMPLETE by checking for the variable_uuid, which is a record id that we are sending via bgapi string.

So we send a bunch of bgapi strings using socket.SendCommand() up to specified limit as to not overload FS. We store the record ID in the list and it gets removed when we receive a response from FS. Some of those variable_uuid do not come in and we have been trying a bunch of solutions, including NEventSocket.

**Comment by danbarua** [comment]
In my testing I found `CHANNEL_HANGUP_COMPLETE` unreliable, which is why all the examples only use `CHANNEL_HANGUP`, hope that helps. :)

**Comment by danbarua** [comment]
Should really get round to writing up all the FS/EventSocket quirks I've uncovered at some point..

**Comment by aistosi** [comment]
Im gonna try this tonight and get back. We've been trying to get this resolved for months. It's gotten so bad, we are losing customers. We are using modified version of FS called Interprexer from this Indian company Phonologies. We keep missing channel_hangup_complete all the time. Also, when NEventSocket started working yesterday, we were getting calls in the subscribe event initially, but later in the day, nothing was coming from that end.

**Comment by aistosi** [comment]
Dan, 

A question for you in the meantime. Do you know if channel_hangup shows up regardless whether callee hangs up or not? I am reading some discussions that channel_hangup_complete only does so when the callee hangs up the call.

**Comment by danbarua** [comment]
Yes, I seem to remember this being the case.

**Comment by aistosi** [comment]
Dan,

Your library seems to work very well. Combining Channel_Hangup and Channel_Answer together we receive 100% of responses for our calls. We have been running our windows service for almost a week with no issues. Thanks again for your help.
