### ISSUE TITLE
ApiResponse.ErrorMessage returns a trailing "\n"

### ISSUE THREAD

**Issue by pragmatrix** [danbarua/NEventSocket#54]
I think the returned ErrorMessage should be either trimmed, or this behavior should be documented.

For example `uuid_break [channel]` returns `-ERR no reply\n` which gets converted to `no reply\n`.

**Comment by danbarua** [comment]
Looks like an inconsistency in the eventsocket protocol there - what FreeSwitch version have you seen with this? I'll need to confirm what's being transmitted over the wire.

**Comment by pragmatrix** [comment]
We are using `FreeSWITCH version: 1.6.9~64bit ( 64bit)`.
