### ISSUE TITLE
ApiResponse: Is "-ERR no reply" an error?

### ISSUE THREAD

**Issue by pragmatrix** [danbarua/NEventSocket#55]
`-ERR no reply` should probably not be treated as an error in `ApiResponse`. I'd suggest to set `Success` to `true` and add another property `IsNoReply` that indicates this specific response state.

**Comment by danbarua** [comment]
From skimming the FreeSwitch source code, it does look that way.

https://github.com/danbarua/NEventSocket/blob/master/src/NEventSocket/Sockets/EventSocket.cs#L151

**Comment by danbarua** [comment]
I think it's ok to just treat `-ERR no reply` as a success.

**Comment by pragmatrix** [comment]
Very good, thank you Dan!
