### ISSUE TITLE
All calls return HangupCause.UnallocatedNumber

### ISSUE THREAD

**Issue by aistosi** [danbarua/NEventSocket#65]
We have another issue. We managed to run our service on another freeswitch server and we are getting HangupCause.UnallocatedNumber for all calls. This is probably freeswitch setup issue but was curious if guys have seen this before.

Thanks,

**Comment by danbarua** [comment]
Yep, definitely a FreeSwitch issue. Turn up debug logging on FreeSwitch and check out `sngrep` for troubleshooting SIP. 

https://github.com/irontec/sngrep

**Comment by aistosi** [comment]
Definitely was a setup issue.
